name: Echo on pull

on:
    pull_request

jobs:
    Placeholder:
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "Will add code checks here in next challenge"